[package]
name          = "nmea-parser"
version       = "0.5.0"
publish       = true
description   = "NMEA 0183 parser for AIS and GNSS sentences"
authors       = ["Timo Saarinen <zaari@mailbox.org>"]
license       = "Apache-2.0"
repository    = "https://github.com/zaari/nmea-parser"
documentation = "https://docs.rs/nmea-parser"
keywords      = ["nmea", "ais", "gnss", "gps"]
categories    = ["parsing"]
readme        = "README.md"
edition       = "2018"
#rust-version  = "1.44"

[dependencies]
bitvec     = "0.19.3"
chrono     = "0.4.19"
log        = "0.4.11"

[dev-dependencies]
assert     = "0.7.4"

