[package]
name          = "nmea-parser"
version       = "0.3.0-dev"
publish       = false
description   = "Rust NMEA sentence parser for AIS and GNSS messages."
authors       = ["Timo Saarinen <zaari@mailbox.org>"]
license       = "Apache-2.0"
repository    = "https://github.com/zaari/nmea-parser"
documentation = "https://docs.rs/nmea-parser"
keywords      = ["nmea", "ais", "gnss", "gps"]
categories    = ["parsing"]
readme        = "README.md"
edition       = "2018"

[dependencies]
bitvec     = "0.19.2"
regex      = "1.3.9"
chrono     = "0.4.19"
log        = "0.4.11"
env_logger = "0.7.1"
assert     = "0.7.4"

[badges]
maintenance = { status = "actively-developed" }

