[package]
name          = "nmea-parser"
version       = "0.1.0"
publish       = true
description   = "Rust NMEA sentence parser for AIS and GNSS messages. Supports AIS class A and B types. Identifies GPS, GLONASS, Galileo, BauDou, Navic and QZSS satellite systems."
authors       = ["Timo Saarinen <zaari@mailbox.org>"]
license       = "Apache-2.0"
#homepage      = ""
repository    = "https://github.com/zaari/nmea-parser"
documentation = "https://docs.rs/nmea-parser"
keywords      = ["nmea", "ais", "gnss", "gps", "glonass", "galileo", "baudou", "navic", "qzss"]
categories    = ["parsing"]
readme        = "README.md"
edition       = "2018"

[dependencies]
bitvec     = "0.19.2"
regex      = "1.3.9"
chrono     = { version = "0.4.19", features = ["serde"] }
log        = "0.4.11"
env_logger = "0.7.1"
assert     = "0.7.4"

[badges]
maintenance = { status = "actively-developed" }

